config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :tasks
  root "tasks#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
  validates_presence_of :name, :due_date, :note
end

class Task < ApplicationRecord
  # 驗證：欄位必須有值
  # 預設不允許空白字元，可用 allow_blank: :true 開啟允許空白
  validates_presence_of :name, :due_date
  # 驗證：長度 20 個字符
  # 英文是 20 個字母，中文則是 20 個字
  validates :name, length: { maximum: 20 }

  # 判斷是否能夠刪除
  # 判斷條件可能有很多，所以將各項判斷分拆到 private method
  def can_destroy?
    # 沒過期的話，回傳 true = 可刪除
    !overdue?
  end

  # 宣告以下為 private method
  # private_method 無法被直接使用
  # `todo.overdue?` 會跳出錯誤: NoMethodError: private method `overdue?`'
  # 可以用 Ruby 原生的 Kernel#send 來呼叫 private_method: todo.send(:overdue?)
  private

  # 如果 due_date 比今天小，則回傳 true = 過期
  def overdue?
    due_date < Date.today
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, :only => [:show, :edit, :update, :destroy]
  def index
    @tasks = Task.order(due_date: :asc)
  end

  def new
    @task = Task.new
  end

  def update
    if @task.update_attributes(task_params)
      flash[:notice] = "succesfully Updated !"
      redirect_to task_path(@task)
    else
      flash[:notice] = "something's missing !"
      render :action => :edit
    end
  end

  def destroy
    if @task.can_destroy?
      @task.destroy
      flash[:alert] = "succesfully Deleted !"
      redirect_to tasks_url
    else
      flash[:alert] = "mission impossible at present !"
    end

  end

  def create
    @task = Task.new(task_params)
    if @task.save
      flash[:notice] = "succesfully Created !"
      redirect_to tasks_url
    else
      render :action => :new
    end
  end

  private

  def task_params
    params.require(:task).permit(:name, :due_date, :note)    
  end

  def set_task
    @task = Task.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper

  # 回傳編輯按鈕
  def task_edit_button(task)
    link_to 'EDIT', edit_task_path(task), class: 'btn btn-primary'
  end

  # 回傳刪除按鈕
  def task_delete_button(task)
    # 無法刪除的 todos 直接回傳 nil，不顯示按鈕
    return unless task.can_destroy?
    link_to 'DEL', task_path(task), class: 'btn btn-danger', method: :delete, data: { confirm: 'You sure to delete it ?' }
  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ToDoList</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/_form.html.erb
<% if @task.errors.present? %>
  <ul>
    <% @task.errors.each do |error, message| %>
      <li> <%= "#{error.capitalize}  #{message}" %></li>
    <% end %>
  </ul>
<% end %>

<div class="form container">
  <%= form_for @task do |f| %>
    <div class="form-group">
      <%= f.label :name, "Name" %>
      <%= f.text_field :name, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :due_date, "Due_date" %>
      <%= f.text_field :due_date, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :note, "Note" %>
      <%= f.text_area :note, class: "form-control" %>
    </div>
      <%= f.submit %>
  <% end %>
</div>

app/views/tasks/edit.html.erb
<%= render :partial => "form" %>

app/views/tasks/index.html.erb
<table class="table table-striped">
  <thead>
    <tr>
      <td>Task Completed</td>
      <td>Task_to_do</td>
      <td>Detail</td>
    </tr>
  </thead>
  <tbody>
  <% @tasks.each do |task| %>
    <tr>
      <td>
        <div class="form-check"></div>
          <label class="form-check-label">
            <input type="checkbox" class="form-check-input">
            check it out!
          </label>  
      </td>
      <td><%= link_to task.name %></td>
      <td><%= link_to 'Show', task_path(task) %></td>
      <td>          
        <div class="actions">
            <%# 把編輯與刪除按鍵搬到 todos_helper.rb %>
            <%# 用 helper 的方式來做按鈕的 render %>
            <%# 可把 todo 物件，當成參數傳入 helper %>
          <%= task_edit_button(task) %>
          <%= task_delete_button(task) %>
        </div>
      </td>
    </tr>
  <% end %>
</table>

<%= link_to 'New Task', new_task_path, class: "btn btn-default" %>

app/views/tasks/new.html.erb
<%= render :partial => "form" %>

app/views/tasks/show.html.erb
      <div class= "modal-header">
        <h2 class= "modal-title"><%= @task.name %></h5>
      </div>

      <div class= "modal-body">
        <h4>Due_date: <b><%= @task.due_date %></b></h4>
        <p><%= simple_format(@task.note) %></p>
      </div>

      <div class= "modal-footer">
        <%= link_to 'Back to index', tasks_path %>
      </div>